import Foundation

/// Bundled breed reference photos and their attribution.
///
/// Generated by tools/photo-sourcing/build_assets.py from Wikimedia Commons
/// metadata — edit the pipeline, not this file.
///
/// Every entry is CC0, public domain, or CC BY. ShareAlike is excluded on
/// purpose: the square crop the detail screen applies is arguably an
/// adaptation, and CC BY-SA 4.0's bar on technological measures is unsettled
/// against App Store DRM. Neither question is worth carrying for decorative
/// photography, and ruling the family out cost exactly one breed.
///
/// Author and licence are shown for every photo in Image Credits, including
/// the CC0 and public-domain ones whose licence compels nothing. Lemon Pig
/// does the same, and the alternative is a screen that quietly credits some
/// photographers and not others.
struct PhotoCredit: Identifiable {
    let id = UUID()
    let imageName: String
    let breed: String
    let author: String
    let license: String
    let sourceURL: String
}

let photoCredits: [PhotoCredit] = [
    PhotoCredit(imageName: "breed-french-bulldog", breed: "French Bulldog", author: "Nan Palmero from San Antonio, TX, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Coco_the_Frenchie_aka_French_Bulldog_(16813076449).jpg"),
    PhotoCredit(imageName: "breed-labrador-retriever", breed: "Labrador Retriever", author: "Rob Hanson", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Labrador_Retriever_chocolate_Hershey_sit.jpg"),
    PhotoCredit(imageName: "breed-golden-retriever", breed: "Golden Retriever", author: "Johan Spaedtke", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Golden_Retriever_adult.jpg"),
    PhotoCredit(imageName: "breed-german-shepherd", breed: "German Shepherd", author: "Hans Kemperman", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:German-shepherd-4040871920.jpg"),
    PhotoCredit(imageName: "breed-poodle", breed: "Poodle", author: "John Leslie", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Standard_Poodle_portrait.jpg"),
    PhotoCredit(imageName: "breed-dachshund", breed: "Dachshund", author: "Tony Alter", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Dachshund_2.jpg"),
    PhotoCredit(imageName: "breed-bulldog", breed: "Bulldog", author: "Koala91", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Mini_Olde_English_Bulldog_1.jpg"),
    PhotoCredit(imageName: "breed-beagle", breed: "Beagle", author: "Mustang Joe", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Beagle_Bailey.jpg"),
    PhotoCredit(imageName: "breed-rottweiler", breed: "Rottweiler", author: "LakshanaRamasamy", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Loyal_Protector_Rottweiler.jpg"),
    PhotoCredit(imageName: "breed-german-shorthaired-pointer", breed: "German Shorthaired Pointer", author: "David Shankbone", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:German_short_haired_pointer_by_David_Shankbone.jpg"),
    PhotoCredit(imageName: "breed-yorkshire-terrier", breed: "Yorkshire Terrier", author: "Lee Ann Ratledge", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Yorkshire_Terrier_Face_-_Knoxville,_Tennessee_-_June_3,_2004.jpg"),
    PhotoCredit(imageName: "breed-boxer", breed: "Boxer", author: "Mostafameraji", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:A_pure_and_female_Boxer_dog_in_Iran_06.jpg"),
    PhotoCredit(imageName: "breed-cavalier-king-charles-spaniel", breed: "Cavalier King Charles Spaniel", author: "Mário Simoes", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Cavalier_King_Charles_Spaniel_at_repose.jpg"),
    PhotoCredit(imageName: "breed-doberman-pinscher", breed: "Doberman Pinscher", author: "JoSaba11", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:DobermannSparte1.jpg"),
    PhotoCredit(imageName: "breed-australian-shepherd", breed: "Australian Shepherd", author: "PxHere", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Australian_Shepherd_in_snow.jpg"),
    PhotoCredit(imageName: "breed-great-dane", breed: "Great Dane", author: "Jon Hurd", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Great_Dane_harlequin_grass.jpg"),
    PhotoCredit(imageName: "breed-miniature-schnauzer", breed: "Miniature Schnauzer", author: "Unknown", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Miniature_Schnauzer_Cindy.jpg"),
    PhotoCredit(imageName: "breed-siberian-husky", breed: "Siberian Husky", author: "localpups", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:3217-siberian-husky-dog_(20314366700).jpg"),
    PhotoCredit(imageName: "breed-bernese-mountain-dog", breed: "Bernese Mountain Dog", author: "FriendlyToaster", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:1-BerneseMountainDogInGrass.jpg"),
    PhotoCredit(imageName: "breed-cane-corso", breed: "Cane Corso", author: "Elmo24105mops", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Cane_Corso_Italiano_Formentino.jpg"),
    PhotoCredit(imageName: "breed-shih-tzu", breed: "Shih Tzu", author: "Mostafameraji", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Shih_Tzu_In_Iran_Mashhad_City_Canon_Photography_Creative_Commons_Photographer_Mostafa_Meraji_05.jpg"),
    PhotoCredit(imageName: "breed-boston-terrier", breed: "Boston Terrier", author: "Wikipedro", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Ocho_Boston_Terrier.jpg"),
    PhotoCredit(imageName: "breed-pomeranian", breed: "Pomeranian", author: "Biswarup Ganguly", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Pomeranian_Dog_-_Kolkata_2011-10-31_6427.JPG"),
    PhotoCredit(imageName: "breed-havanese", breed: "Havanese", author: "Pets Adviser from Brooklyn, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Havanese-12-GCH-_Ji_Jo%27s_and_Shatara%27s_High_Voltage_05_(15962682524).jpg"),
    PhotoCredit(imageName: "breed-english-springer-spaniel", breed: "English Springer Spaniel", author: "Alexander king", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Black_and_White_English_Springer_Spaniel.jpg"),
    PhotoCredit(imageName: "breed-shetland-sheepdog", breed: "Shetland Sheepdog", author: "Loowgren", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Shetland_Sheepdog2.jpg"),
    PhotoCredit(imageName: "breed-cocker-spaniel", breed: "Cocker Spaniel", author: "Jean-Pol GRANDMONT", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:%22Bill%22_-_Cocker_spaniel_anglais_1.jpg"),
    PhotoCredit(imageName: "breed-border-collie", breed: "Border Collie", author: "Joselodos", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Border_collie_sitting_on_the_grass.jpg"),
    PhotoCredit(imageName: "breed-chihuahua", breed: "Chihuahua", author: "Lee Kok Seng Moe", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Chihuahua-dog.jpg"),
    PhotoCredit(imageName: "breed-basset-hound", breed: "Basset Hound", author: "Codyman", license: "CC BY 2.5", sourceURL: "https://commons.wikimedia.org/wiki/File:Basset_Hound_(1).jpg"),
    PhotoCredit(imageName: "breed-pembroke-welsh-corgi", breed: "Pembroke Welsh Corgi", author: "Mrkoww", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Tan_Pembroke_Welsh_Corgi.jpg"),
    PhotoCredit(imageName: "breed-vizsla", breed: "Vizsla", author: "Florrez Maximal", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:Male_four_year_old_Vizsla.jpg"),
    PhotoCredit(imageName: "breed-pug", breed: "Pug", author: "Mohandoss Sampath", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Pug_Dog_(66231737).jpeg"),
    PhotoCredit(imageName: "breed-australian-cattle-dog", breed: "Australian Cattle Dog", author: "tkcrash123", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Australian_Cattle_Dog_portrait.jpg"),
    PhotoCredit(imageName: "breed-maltese", breed: "Maltese", author: "Toby Weisenhaus", license: "CC BY 2.5", sourceURL: "https://commons.wikimedia.org/wiki/File:Maltese_dog_enjoying_the_fall_leaves,_Nov._2004-1.jpg"),
    PhotoCredit(imageName: "breed-weimaraner", breed: "Weimaraner", author: "cadillacdeville2000", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Weimaraner2.jpg"),
    PhotoCredit(imageName: "breed-collie", breed: "Collie", author: "Redacted (Jim Twitchell)", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Rough_Collie_portrait.jpg"),
    PhotoCredit(imageName: "breed-newfoundland", breed: "Newfoundland", author: "DanDee Shots", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Newfoundland_dog_Smoky.jpg"),
    PhotoCredit(imageName: "breed-rhodesian-ridgeback", breed: "Rhodesian Ridgeback", author: "Gulik", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Rhodesian_ridgeback_head_study.jpg"),
    PhotoCredit(imageName: "breed-great-pyrenees", breed: "Great Pyrenees", author: "Denis789", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Rhune_Agropastoralisme_Lug,_berger_des_Pyr%C3%A9n%C3%A9es.jpg"),
    PhotoCredit(imageName: "breed-mastiff", breed: "Mastiff", author: "ocean yamaha", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:English_Mastiff_Image_001.jpg"),
    PhotoCredit(imageName: "breed-akita", breed: "Akita", author: "Azurfrog", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Akita_Inu_(male).jpg"),
    PhotoCredit(imageName: "breed-saint-bernard", breed: "Saint Bernard", author: "Alan Levine", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:St_Bernard_Dog.jpg"),
    PhotoCredit(imageName: "breed-bloodhound", breed: "Bloodhound", author: "John Leslie", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Bloodhound_Trials_Feb_2008_-79.jpg"),
    PhotoCredit(imageName: "breed-jack-russell-terrier", breed: "Jack Russell Terrier", author: "Plank", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Jack_Russell_Terrier_1.jpg"),
    PhotoCredit(imageName: "breed-shiba-inu", breed: "Shiba Inu", author: "Guilhem Vellut from Annecy, France", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Shiba_Inu_dog_@_Mount_Mitake_(13438986414).jpg"),
    PhotoCredit(imageName: "breed-pit-bull", breed: "Pit Bull", author: "Stacy", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:002_American_Pit_Bull_Terrier.jpg"),
    PhotoCredit(imageName: "breed-american-staffordshire-terrier", breed: "American Staffordshire Terrier", author: "Joselodos", license: "CC0", sourceURL: "https://commons.wikimedia.org/wiki/File:American_Staffordshire_terrier_portrait.jpg"),
    PhotoCredit(imageName: "breed-staffordshire-bull-terrier", breed: "Staffordshire Bull Terrier", author: "claralieu", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Staffordshire_Bull_Terrier_03.jpg"),
    PhotoCredit(imageName: "breed-goldendoodle", breed: "Goldendoodle", author: "Sarahcg2021", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Petite_Standard_Goldendoodle_Cream.jpg"),
    PhotoCredit(imageName: "breed-labradoodle", breed: "Labradoodle", author: "Anton Porsche", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Labradoodle-braun.jpg"),
    PhotoCredit(imageName: "breed-bernedoodle", breed: "Bernedoodle", author: "Missvain", license: "CC BY 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:2019_Laurent-Perrier_Pop-Up_in_Sonoma_-_Sarah_Stierch_06.jpg"),
    PhotoCredit(imageName: "breed-plott-hound", breed: "Plott Hound", author: "James Emery", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Plott_Hound.jpg"),
    PhotoCredit(imageName: "breed-catahoula-leopard-dog", breed: "Catahoula Leopard Dog", author: "Olgierd (Creative Commons licensed only)", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Louisiana_Catahoula_Leopard_dog_(48809112562).jpg"),
    PhotoCredit(imageName: "breed-chinese-crested", breed: "Chinese Crested", author: "Sheri Terris", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Chinese_Crested_Dog.jpg"),
]
