import Foundation

/// Bundled breed reference photos and their attribution.
///
/// Generated by tools/photo-sourcing/build_assets.py from Wikimedia Commons
/// metadata — edit the pipeline, not this file. Every entry is CC0, public
/// domain, CC BY or CC BY-SA; nothing here is NonCommercial, NoDerivs, or
/// AKC's own photography.
///
/// Author and licence are shown for every photo in Image Credits, including
/// the public-domain ones whose licence compels nothing. Lemon Pig does the
/// same, and the alternative is a screen that quietly credits some
/// photographers and not others.
struct PhotoCredit: Identifiable {
    let id = UUID()
    let imageName: String
    let breed: String
    let author: String
    let license: String
    let sourceURL: String
}

let photoCredits: [PhotoCredit] = [
    PhotoCredit(imageName: "breed-french-bulldog", breed: "French Bulldog", author: "Delimata", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:French_Bulldog.JPG"),
    PhotoCredit(imageName: "breed-labrador-retriever", breed: "Labrador Retriever", author: "Jason Oatman", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Black_Labrador_Retriever_portrait.jpg"),
    PhotoCredit(imageName: "breed-golden-retriever", breed: "Golden Retriever", author: "MichaelMcPhee", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Callie_the_golden_retriever_puppy.jpg"),
    PhotoCredit(imageName: "breed-german-shepherd", breed: "German Shepherd", author: "Jakub Hałun", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:20110425_German_Shepherd_Dog_8505.jpg"),
    PhotoCredit(imageName: "breed-poodle", breed: "Poodle", author: "John Leslie from London, UK", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Standard_poodle_apricot.jpg"),
    PhotoCredit(imageName: "breed-dachshund", breed: "Dachshund", author: "Medium69 (William Crochot)", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Teckel_-_39.jpg"),
    PhotoCredit(imageName: "breed-bulldog", breed: "Bulldog", author: "Buckandsons", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:CH_Buck_and_Sons_Evita_Peron.jpg"),
    PhotoCredit(imageName: "breed-beagle", breed: "Beagle", author: "Soccersmp", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Beagle_puppy_Cadet_2.jpg"),
    PhotoCredit(imageName: "breed-rottweiler", breed: "Rottweiler", author: "Twin Jalanugraha", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Rottweiler_2.jpg"),
    PhotoCredit(imageName: "breed-german-shorthaired-pointer", breed: "German Shorthaired Pointer", author: "Orihesh", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:German_shorthaired_pointer_louis.JPG"),
    PhotoCredit(imageName: "breed-yorkshire-terrier", breed: "Yorkshire Terrier", author: "Bc. Kateřina Filipi", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Colorful_yorkshire_terrier_-_Tricolor.jpg"),
    PhotoCredit(imageName: "breed-boxer", breed: "Boxer", author: "Jena Fuller", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:%22Boxer_dog%22_stand.jpg"),
    PhotoCredit(imageName: "breed-cavalier-king-charles-spaniel", breed: "Cavalier King Charles Spaniel", author: "Ric17", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Cavalier_King_Charles_Spaniel_with_ball.jpg"),
    PhotoCredit(imageName: "breed-doberman-pinscher", breed: "Doberman Pinscher", author: "Stonda~commonswiki", license: "CC BY 2.5", sourceURL: "https://commons.wikimedia.org/wiki/File:Dobermann_standing.jpg"),
    PhotoCredit(imageName: "breed-australian-shepherd", breed: "Australian Shepherd", author: "Mike from Baltimore, USA", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Miniature_Australian_Shepherd_blue_merle.jpg"),
    PhotoCredit(imageName: "breed-great-dane", breed: "Great Dane", author: "YourNetBuddy", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Great_Dane_Isabelle.JPG"),
    PhotoCredit(imageName: "breed-miniature-schnauzer", breed: "Miniature Schnauzer", author: "jono2k5 (Jonathan Oakley)", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Miniature_Schnauzer_Jordy.jpg"),
    PhotoCredit(imageName: "breed-siberian-husky", breed: "Siberian Husky", author: "m.prinke", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Siberian_Husky_wolfgray_Sweden.jpg"),
    PhotoCredit(imageName: "breed-bernese-mountain-dog", breed: "Bernese Mountain Dog", author: "Antonio Kless", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Bernese_Mountain_Dog_Female.jpg"),
    PhotoCredit(imageName: "breed-cane-corso", breed: "Cane Corso", author: "Pleple2000", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Cane_corso_g%C5%82owa_profil_493o.jpg"),
    PhotoCredit(imageName: "breed-shih-tzu", breed: "Shih Tzu", author: "Wawri (Tomasz Wawak)", license: "CC BY-SA 2.5", sourceURL: "https://commons.wikimedia.org/wiki/File:Shih-tzu-Fibi.jpg"),
    PhotoCredit(imageName: "breed-boston-terrier", breed: "Boston Terrier", author: "Chitrapa at English Wikipedia", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Joe-Joe_the_Boston_Terrier_(age_2).jpg"),
    PhotoCredit(imageName: "breed-pomeranian", breed: "Pomeranian", author: "Rob Hanson", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Pomeranian_orange-sable_Coco.jpg"),
    PhotoCredit(imageName: "breed-havanese", breed: "Havanese", author: "Bagienny", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Bichon_havanese_cezar.jpg"),
    PhotoCredit(imageName: "breed-english-springer-spaniel", breed: "English Springer Spaniel", author: "Hhoefling", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:English-Springer-Spaniel_Penny1.jpg"),
    PhotoCredit(imageName: "breed-shetland-sheepdog", breed: "Shetland Sheepdog", author: "jimthompson", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Shetland_Sheepdog_tricolour.jpg"),
    PhotoCredit(imageName: "breed-cocker-spaniel", breed: "Cocker Spaniel", author: "Pleple2000", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Cocker_spaniel_angielski_zlotyy.jpg"),
    PhotoCredit(imageName: "breed-border-collie", breed: "Border Collie", author: "Baden de", license: "CC BY 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Border_Collie_-_panoramio.jpg"),
    PhotoCredit(imageName: "breed-chihuahua", breed: "Chihuahua", author: "Federicolozanob", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Chihuahua_Dog_Face.jpg"),
    PhotoCredit(imageName: "breed-basset-hound", breed: "Basset Hound", author: "eda", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Basset_hound_2ans.jpeg"),
    PhotoCredit(imageName: "breed-pembroke-welsh-corgi", breed: "Pembroke Welsh Corgi", author: "Pleple2000", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Welsh_corgi_pembroke_portret_00pl.jpg"),
    PhotoCredit(imageName: "breed-vizsla", breed: "Vizsla", author: "MyName (M.Fuchten)", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Vizsla_dog_in_grass.JPG"),
    PhotoCredit(imageName: "breed-pug", breed: "Pug", author: "Unknown", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Pug_black_600.jpg"),
    PhotoCredit(imageName: "breed-australian-cattle-dog", breed: "Australian Cattle Dog", author: "tkcrash123", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Australian_Cattle_Dog_portrait.jpg"),
    PhotoCredit(imageName: "breed-maltese", breed: "Maltese", author: "Toby Weisenhaus", license: "CC BY 2.5", sourceURL: "https://commons.wikimedia.org/wiki/File:Maltese_dog_enjoying_the_fall_leaves,_Nov._2004-1.jpg"),
    PhotoCredit(imageName: "breed-weimaraner", breed: "Weimaraner", author: "Christopher Sibley", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Weimaraner_posing.jpg"),
    PhotoCredit(imageName: "breed-collie", breed: "Collie", author: "Christian Madden", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Rough_Collie_KC.jpg"),
    PhotoCredit(imageName: "breed-newfoundland", breed: "Newfoundland", author: "DanDee Shots", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Newfoundland_dog_Smoky.jpg"),
    PhotoCredit(imageName: "breed-rhodesian-ridgeback", breed: "Rhodesian Ridgeback", author: "Pleple2000", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Rhodesian_ridgeback_g%C5%82owa_76.jpg"),
    PhotoCredit(imageName: "breed-great-pyrenees", breed: "Great Pyrenees", author: "Carly & Art", license: "CC BY-SA 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Great_Pyrenees_portrait.jpg"),
    PhotoCredit(imageName: "breed-mastiff", breed: "Mastiff", author: "ocean yamaha", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:English_Mastiff_Image_001.jpg"),
    PhotoCredit(imageName: "breed-akita", breed: "Akita", author: "Biser Yanev", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Akita_Inu_dog.jpg"),
    PhotoCredit(imageName: "breed-saint-bernard", breed: "Saint Bernard", author: "Daniel Steger", license: "CC BY-SA 2.5", sourceURL: "https://commons.wikimedia.org/wiki/File:St_Bernard_with_barrel.JPG"),
    PhotoCredit(imageName: "breed-bloodhound", breed: "Bloodhound", author: "Pypaertv , modyfikacja Pleple2000", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Bloodhound_423.jpg"),
    PhotoCredit(imageName: "breed-jack-russell-terrier", breed: "Jack Russell Terrier", author: "Radosław Drożdżewski (Zwiadowca21)", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Jack_Russell_Terrier_Demi.jpg"),
    PhotoCredit(imageName: "breed-shiba-inu", breed: "Shiba Inu", author: "Roberto Vasarri", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Shiba_inu_taiki.jpg"),
    PhotoCredit(imageName: "breed-pit-bull", breed: "Pit Bull", author: "Photo by Dante Alighieri", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:American_Pit_Bull_Terrier_-_Seated.jpg"),
    PhotoCredit(imageName: "breed-american-staffordshire-terrier", breed: "American Staffordshire Terrier", author: "Conny48592", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:American_Staffordshire_Terrier(Cleo).JPG"),
    PhotoCredit(imageName: "breed-staffordshire-bull-terrier", breed: "Staffordshire Bull Terrier", author: "Aixeneta", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Staffie.jpg"),
    PhotoCredit(imageName: "breed-goldendoodle", breed: "Goldendoodle", author: "Glenn1480", license: "Public domain", sourceURL: "https://commons.wikimedia.org/wiki/File:Goldendoodle_bone.jpg"),
    PhotoCredit(imageName: "breed-labradoodle", breed: "Labradoodle", author: "Endless Dan", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Labradoodle_Scrappy.jpg"),
    PhotoCredit(imageName: "breed-plott-hound", breed: "Plott Hound", author: "James Emery", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Plott_Hound.jpg"),
    PhotoCredit(imageName: "breed-catahoula-leopard-dog", breed: "Catahoula Leopard Dog", author: "Alina78", license: "CC BY-SA 3.0", sourceURL: "https://commons.wikimedia.org/wiki/File:LennoxWinter.jpg"),
    PhotoCredit(imageName: "breed-mountain-cur", breed: "Mountain Cur", author: "ThoHug", license: "CC BY-SA 4.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Mtncur.png"),
    PhotoCredit(imageName: "breed-chinese-crested", breed: "Chinese Crested", author: "Sheri Terris", license: "CC BY 2.0", sourceURL: "https://commons.wikimedia.org/wiki/File:Chinese_Crested_Dog.jpg"),
]
